name: CI

on:
  push:
    branches:
      - develop
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        python --version
        pip install ansible
        apt-get update && apt-get install -y rsync
