name: CI

on:
  push:
    branches:
      - develop
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |

- name: Install dependencies
  run: |
        python -m pip install --upgrade pip
        pip install ansible
        apt-get update && apt-get install -y rsync
