name: CI

on:
  push:
    branches:
      - develop
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        run: |
          cd ansible
          echo "${{ secrets.DEV_SERVER_SSH_KEY }}" > id_rsa
          chmod 400 id_rsa
          ansible-playbook deploy.yml -i inventory --extra-vars "target=dev-web-server" --private-key=id_rsa
        env:
          ANSIBLE_HOST_KEY_CHECKING: False