name: CI

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/ansible
        env:
          DEV_SERVER_SSH_KEY: ${{ secrets.DEV_SERVER_SSH_KEY }}

