name: CI

on:
  push:
    branches:
      - develop
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
            python --version
            ansible --version
            pwd
            mkdir -p ~/.ssh
            umask  077 ; echo  ${{ secrets.DEV_SERVER_SSH_KEY }} > ~/.ssh/id_rsa
            cd ansible
            pwd
            ansible-playbook deploy-site.yml -i inventory --extra-vars "target=dev-web-server" --private-key=~/.ssh/id_rsa
