name: CI

on:
  push:
    branches:
      - develop
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Checkout
      uses: actions/checkout@v1
      run: |
            cd ansible
            pwd
            ansible-playbook deploy-site.yml -i inventory --extra-vars "target=dev-web-server" --private-key=~/.ssh/id_rsa

